### ISSUE TITLE
TypeError: Cannot read property 'room_id' of undefined

### ISSUE THREAD

**Issue by jwildeboer** [ivesdebruycker/node-red-contrib-maxcube#8]
Using the version of node-red-contrib-maxcube on npm as of today (2016-11-30) on Node Red 0.15.2, I get the above error in the Node Red debug console. Due to this, it seems I cannot send commands to my thermostats. This is also mentioned in https://github.com/ivesdebruycker/maxcube/issues/12 which I guess is the same problem/bug.

I also see entries like

`{ "rf_address": "0ba773" }`

Which I guess are my window sensors that AFAICS are not (yet) supported?

**Comment by jwildeboer** [comment]
Using the cli tool I get correct data. I can also succesfully change the temperature setting on my thermostats. And I also see that my window sensors are treated as thermostats with undefined data but not showing the open or close status I would expect to see. It also seems that the wall thermostats are not showing any uselfull information or settings.

> maxcube$ status
 0ba773 (Wall Thermostat, Living Room) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0c9362 (Eco Switch, null) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0c98c6 (Bathroom, Bathroom) - temp: 0, setpoint: 10, valve: 0, mode: AUTO
16547f (BalconyDoor, Living Room) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0c98bd (Kitchen, Kitchen) - temp: 0, setpoint: 14, valve: 0, mode: AUTO
0ba823 (Bedroom Wall, Bedroom) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0cb005 (Kitchen Window, Kitchen) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0ca84e (Bedroom, Bedroom) - temp: 0, setpoint: 14, valve: 14, mode: AUTO
0ca05a (Bedroom Window, Bedroom) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
018999 (Window Sensor, Bathroom) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0c975a (Balcony, Living Room) - temp: 0, setpoint: 14, valve: 0, mode: AUTO
018973 (WindowSensor, Living Room) - temp: undefined, setpoint: undefined, valve: undefined, mode: undefined
0c9768 (Desk, Living Room) - temp: 0, setpoint: 14, valve: 0, mode: AUTO

**Comment by jwildeboer** [comment]
I can reliably reproduce this error by simply sending this payload (as JSON) to a maxcube-in node:

`{"rfid":"0ca84e","degrees": 15 }`

Immediate result:

Nov 30 18:36:28 rpi.home.lan nodered[2563]: 30 Nov 18:36:28 - [error] [maxcube in:129689aa.d5e406] TypeError: Cannot read property 'room_id' of undefined

And the temperature doesn't get set :-(

**Comment by ivesdebruycker** [comment]
This should be fixed with an update to the latest release of maxcube lib ([1.0.3](https://github.com/ivesdebruycker/maxcube/releases/tag/1.0.3)).
Can you perform `npm update` in the node-red-contrib-maxcube folder and try again?

**Comment by jwildeboer** [comment]
Seems it doesn't fix the problem for me :-( I have updated maxcube, node-red-contrib-maxcube. Rebooted the machine, deleted the nodes, added them as new nodes, still the undefined error in node-red.

The error happens when I send a JSON payload of

`{"rfid":"0ca84e","degrees": 15 }`

To a Maxcube Output node

When I use the maxcube-cli it all works.

**Comment by jwildeboer** [comment]
Here the flow in node-red:

[{"id":"ce05ef78.7bab4","type":"link in","z":"b96f9c86.269df","name":"SetMaxCube","links":[],"x":615,"y":120,"wires":[["26cc5c00.ffb884"]]},{"id":"26cc5c00.ffb884","type":"maxcube in","z":"b96f9c86.269df","server":"3e2fbbb0.322774","x":740,"y":120,"wires":[]},{"id":"f731e745.b4c3f8","type":"inject","z":"b96f9c86.269df","name":"SetTemp","topic":"","payload":"{\"rfid\":\"0ca84e\",\"degrees\": 15 }","payloadType":"json","repeat":"","crontab":"","once":false,"x":560,"y":160,"wires":[["26cc5c00.ffb884"]]},{"id":"3e2fbbb0.322774","type":"maxcube-server","z":"","host":"192.168.1.250","port":"62910"}]

**Comment by jwildeboer** [comment]
Yes. That seems to fix it. Thank you!
